FROM node:12

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .

COPY dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/dev.sh
ENTRYPOINT ["dev.sh"]

CMD ["npm", "run", "dev"]
