FROM node:12

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

RUN apt-get update && apt-get install -y netcat && apt-get clean

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .

COPY staging.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/staging.sh
ENTRYPOINT ["staging.sh"]

CMD ["npm", "run", "start"]
